server:
  port: 8084

spring:
  application:
    name: integration-service
  datasource:
    url: jdbc:postgresql://localhost:5432/plp_db?currentSchema=plp_integration
    username: plp_admin
    password: plp_secret_2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: plp_integration
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    schemas: plp_integration
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: plp_rabbit
    password: plp_rabbit_2026

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
