ALTER TABLE invoices ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS last_finance_requested_at TIMESTAMPTZ;
