server {
    listen 80;
    location = /env-config.js {
        alias /usr/share/nginx/html/env-config.js;
    }
    location /plp-anchor/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /plp-anchor/index.html;
    }
    location = /plp-anchor {
        return 301 /plp-anchor/;
    }
    location / {
        return 301 /plp-anchor/;
    }
}
