server {
    listen 80;
    location = /env-config.js {
        alias /usr/share/nginx/html/env-config.js;
    }
    location /plp/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /plp/index.html;
    }
    location = /plp {
        return 301 /plp/;
    }
    location / {
        return 301 /plp/;
    }
}
