server {
    listen 80;
    location = /env-config.js {
        alias /usr/share/nginx/html/env-config.js;
    }
    location /plp-borrower/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /plp-borrower/index.html;
    }
    location = /plp-borrower {
        return 301 /plp-borrower/;
    }
    location / {
        return 301 /plp-borrower/;
    }
}
