spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/plp_db?currentSchema=plp_program
  data:
    redis:
      port: 6380
  rabbitmq:
    port: 5673

server:
  port: 8182

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka/

plp:
  iam:
    base-url: http://localhost:8181
  lending:
    base-url: http://localhost:8183
  dev-reset:
    enabled: true
  storage:
    local:
      root: ./uploads/digital-invoices
    minio:
      endpoint: http://localhost:9010
