server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/plp_db?currentSchema=plp_notification
    username: plp_admin
    password: plp_secret_2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: plp_notification
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    schemas: plp_notification
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: plp_rabbit
    password: plp_rabbit_2026
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:billiontechuat@gmail.com}
    password: ${SMTP_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

plp:
  notification:
    email:
      from-address: ${EMAIL_FROM_ADDRESS:billiontechuat@gmail.com}
      from-name: ${EMAIL_FROM_NAME:PLP Platform}
      simulation-enabled: ${EMAIL_SIMULATION_ENABLED:false}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
